services:
  backend:
    build: saythanks-backend
    environment:
      - USPS_CLIENT_ID=${USPS_CLIENT_ID-}
      - USPS_CLIENT_SECRET=${USPS_CLIENT_SECRET-}
    ports:
      - "8080:8080"

  frontend:
    build: saythanks-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production